import pandas as pd


image_shape_color_features = pd.DataFrame({
    "magnitude_mean": [],
    "magnitude_median": [],

    "h_mean": [],
    "h_std": [],
    "h_skewness": [],
    "h_kurtosis": [],
    "s_mean": [],
    "s_std": [],
    "s_skewness": [],
    "s_kurtosis": [],
    "v_mean": [],
    "v_std": [],
    "v_skewness": [],
    "v_kurtosis": [],

    "ring_1_magnitude_mean": [],
    "ring_1_magnitude_median": [],
    "ring_1_orientation_mean": [],
    "ring_1_orientation_median": [],
    "ring_1_h_mean": [],
    "ring_1_h_std": [],
    "ring_1_h_skewness": [],
    "ring_1_h_kurtosis": [],
    "ring_1_s_mean": [],
    "ring_1_s_std": [],
    "ring_1_s_skewness": [],
    "ring_1_s_kurtosis": [],
    "ring_1_v_mean": [],
    "ring_1_v_std": [],
    "ring_1_v_skewness": [],
    "ring_1_v_kurtosis": [],

    "ring_2_magnitude_mean": [],
    "ring_2_magnitude_median": [],
    "ring_2_orientation_mean": [],
    "ring_2_orientation_median": [],
    "ring_2_h_mean": [],
    "ring_2_h_std": [],
    "ring_2_h_skewness": [],
    "ring_2_h_kurtosis": [],
    "ring_2_s_mean": [],
    "ring_2_s_std": [],
    "ring_2_s_skewness": [],
    "ring_2_s_kurtosis": [],
    "ring_2_v_mean": [],
    "ring_2_v_std": [],
    "ring_2_v_skewness": [],
    "ring_2_v_kurtosis": [],

    "ring_3_magnitude_mean": [],
    "ring_3_magnitude_median": [],
    "ring_3_orientation_mean": [],
    "ring_3_orientation_median": [],
    "ring_3_h_mean": [],
    "ring_3_h_std": [],
    "ring_3_h_skewness": [],
    "ring_3_h_kurtosis": [],
    "ring_3_s_mean": [],
    "ring_3_s_std": [],
    "ring_3_s_skewness": [],
    "ring_3_s_kurtosis": [],
    "ring_3_v_mean": [],
    "ring_3_v_std": [],
    "ring_3_v_skewness": [],
    "ring_3_v_kurtosis": [],

    "ring_4_magnitude_mean": [],
    "ring_4_magnitude_median": [],
    "ring_4_orientation_mean": [],
    "ring_4_orientation_median": [],
    "ring_4_h_mean": [],
    "ring_4_h_std": [],
    "ring_4_h_skewness": [],
    "ring_4_h_kurtosis": [],
    "ring_4_s_mean": [],
    "ring_4_s_std": [],
    "ring_4_s_skewness": [],
    "ring_4_s_kurtosis": [],
    "ring_4_v_mean": [],
    "ring_4_v_std": [],
    "ring_4_v_skewness": [],
    "ring_4_v_kurtosis": [],

    "ring_5_magnitude_mean": [],
    "ring_5_magnitude_median": [],
    "ring_5_orientation_mean": [],
    "ring_5_orientation_median": [],
    "ring_5_h_mean": [],
    "ring_5_h_std": [],
    "ring_5_h_skewness": [],
    "ring_5_h_kurtosis": [],
    "ring_5_s_mean": [],
    "ring_5_s_std": [],
    "ring_5_s_skewness": [],
    "ring_5_s_kurtosis": [],
    "ring_5_v_mean": [],
    "ring_5_v_std": [],
    "ring_5_v_skewness": [],
    "ring_5_v_kurtosis": [],
})